import turtle
def rect(color):
    flag.begin_fill()
    flag.fillcolor(color)
    for i in range(2):
        flag.fd(200)
        flag.right(90)
        flag.fd(50)
        flag.right(90)
    flag.end_fill()

def rect_2(distance,angle = 90):
    flag.fd(distance)
    flag.right(angle)

def text(x,y,color,content,al):
    flag.up()
    flag.goto(x,y)
    flag.down()
    style = ('TimesNewRoman',30,'italic')
    flag.color(color)
    flag.write(content,font = style,align = al)

flag = turtle.Turtle()
wn = turtle.Screen()
wn.bgcolor('black')
wn.title('Indian Flag')
flag.pensize(6)
flag.color('white')
flag.up()
flag.goto(0,-200)
flag.fd(-200)
flag.down()
flag.fillcolor('white')
for i in range(2):
    flag.fd(400)
    flag.rt(90)
    flag.fd(20)
    flag.rt(90)
flag.fd(200)
flag.fd(-100)
flag.lt(90)
for i in range(2):
    flag.fd(20)
    flag.rt(90)
    flag.fd(200)
    flag.rt(90)
flag.fd(20)
flag.rt(90)
flag.fd(100)

flag.goto(0,200)
flag.pensize(2)
rect("#FF9933")
flag.begin_fill()
flag.fillcolor('white')
flag.goto(0,150)
flag.fd(100)
flag.color("#000080")
flag.circle(-25)
flag.setheading(270)
flag.fd(25)
flag.setheading(0)
for i in range(24):
    flag.fd(25)
    flag.bk(25)
    flag.left(15)
flag.setheading(90)
flag.fd(25)
flag.setheading(0)
flag.color("white")

rect_2(100)
rect_2(50)
rect_2(200)
rect_2(50)
flag.end_fill()
flag.goto(0,100)
rect("#138808")
text(150,-40,'#FF9933','Happy','left')
text(200,-80,'#FFFFFF','Independence','center')
text(200,-120,'#138808','Day','right')
flag.ht()

wn.exitonclick()
